import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#232323',
    paddingTop: 60,
  },
  formTitle: {
    fontSize: 32,
    color: '#c2c2c2ff',
    fontWeight: 'bold',
    marginBottom: 24,
    alignSelf: 'center',
    letterSpacing: 1,
  },
  sectionContainer: {
    backgroundColor: '#181818',
    borderRadius: 14,
    padding: 18,
    marginBottom: 22,
    width: '92%',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
  },
  sectionTitle: {
    color: '#c2c2c2ff',
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 12,
    alignSelf: 'center',
    letterSpacing: 0.5,
  },
  inputGroup: {
    marginBottom: 14,
  },
  label: {
    color: '#696969ff',
    fontSize: 15,
    fontWeight: '500',
    marginBottom: 2,
    marginLeft: 2,
    letterSpacing: 0.2,
  },
  input: {
    backgroundColor: '#232323',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: '#929292ff',
    borderWidth: 1.5,
    borderColor: '#232323',
    fontSize: 16,
    marginTop: 4,
  },
  inputError: {
    borderColor: '#ff4d4d',
  },
  errorText: {
    color: '#ff4d4d',
    fontSize: 12,
    marginTop: 2,
    marginLeft: 2,
  },
  infoText: {
    color: '#bdbdbd',
    fontSize: 12,
    marginTop: 2,
    marginLeft: 2,
  },
  submitButton: {
    backgroundColor: '#ff4747',
    borderRadius: 22,
    paddingVertical: 14,
    paddingHorizontal: 40,
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 30,
    width: '80%',
    alignSelf: 'center',
    shadowColor: '#ff4747',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 2,
  },
  submitButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
    letterSpacing: 1,
  },
  required: {
    color: '#ff4d4d',
    fontWeight: 'bold',
  },
});
